version: '3.9'

services:
  elympicsapi:
    image: elympics-api:latest
    container_name: elympics-api
    build:
      context: .
      dockerfile: ./Elympics.Api/Dockerfile
    ports:
      - "5002:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - postgres

  elympicsrandom:
    image: elympics-random:latest
    container_name: random-api
    build:
      context: .
      dockerfile: ./Elympics.RandomNumber.Api/Dockerfile
    ports:
      - "8006:5001"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: randomnumber
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"